name: siamese502-kfold-on-4

dataset:
  folder: camera-1-light-on
  grayscale: False
  class: model.datasets.pallet502.SiameseDataset
  args:
    dup: 5
    path_to_subsets: kfold_fn/light_on_fold_4.json
  transform:
  - name: resize
    height: 230
    width: 400

training:
  data_loader:
    batch_size: 256
    shuffle: True
  epoch: 30
  criterion: torch.nn.TripletMarginLoss

model:
  name: model.siamese.Siamese502
  args:
    img_num_channel: 3
  folder: tmp/
