name: siamese502-colorbased-A-on-0

dataset:
  folder: camera-1-light-on
  grayscale: False
  class: model.datasets.pallet502.SelectiveSiameseDataset
  args:
    dup: 5
    path_to_subsets: kfold_fn/light_on_fold_0.json
  transform:
    - name: resize
      height: 256
      width: 192
    - name: colorbased
      h: 16
      w: 16
      feature_type: average-color

training:
  data_loader:
    batch_size: 256
    shuffle: True
  epoch: 80
  criterion:
    name: torch.nn.TripletMarginLoss
    reduction: none
    margin: 2

model:
  name: model.siamese.SiameseColorbased
  folder: tmp/A
